version: '3.5'

services:
  mongodb:
    image: mongo:latest
    container_name: db
    hostname: db
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    restart: on-failure
    networks:
      - movie_network
    # ports:
    #   - "27017:27017"
    volumes:
      - ./db/data:/data/db
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    hostname: backend
    networks:
      - movie_network
    ports:
      - "9090:9090"
    restart: on-failure
    depends_on:
      - mongodb
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - movie_network
    ports:
      - "80:80"
    restart: on-failure
    depends_on:
      - backend
    links:
      - backend
    
networks:
  movie_network:
    
